### PR TITLE
Changes to make environment work on platform

### PR DESCRIPTION
**Pull request by mandrew**
added dynamodb module, updated config to use SS_DATABASE_NAME, pointed docsviewer to assets folder, updated robots.txt to disallow assets

### CODE REVIEW

**Comment by tractorcow** [comment]
You need to fix your PR mate. :) Did you mean to merge into master?

**Comment by mandrew** [comment]
@tractorcow hmm this should be trying to merge into a branch called feature/platform which I created from master, rather then merging straight into master? (just yet anyway).

**Comment by mandrew** [comment]
also conflict has been resolved

**Comment by tractorcow** [comment]
Looks good.

**Pull request merged**
