### PR TITLE
Making the docs site ready for SilverStripe Platform

### PR DESCRIPTION
**Pull request by camfindlay**
We are going to be powering the SilverStripe community sites on [SilverStripe Platform](http://www.silverstripe.com/platform). This branch adds the required modules to make it platform ready along with a rework of the previous shell script into a SilverStripe build task (and for Platform compatibility).

Once merged we'll tag this as a major release of this project.

### CODE REVIEW

**Comment by camfindlay** [comment]
Will need to resolve conflicts.

**Comment by camfindlay** [comment]
Currently testing this branch, will update once I know it's all okay and ready to merge.

**Comment by camfindlay** [comment]
Seems good to go. Anyone keen to do a final review and thumbs up on this... @assertchris ? :)

**Comment by assertchris** [comment]
:+1:

**Comment by camfindlay** [comment]
@mandrew can you please merge this.

**Comment by camfindlay** [comment]
or... @assertchris

**Pull request merged**
