### PR TITLE
FIXED : Issue 50

### PR DESCRIPTION
**Pull request by SpiritLevel**

### CODE REVIEW

**Comment by camfindlay** [comment]
Nice one! I'll test locally and then we can look at merging.

**Comment by SpiritLevel** [comment]
Gidday Cam. I am fiddling with git at the command line, in a graphical tool, and phpstorm all at the same time...and I have been creating lots of messes! Anyhow, that explains all the closed PRs. 

Test, merge, and generate another top 50! Let's get 'em all while focussed on it ;)

I think I'd like to tidy up the explanation here: http://docs.silverstripe.org/en/3.1/contributing/code/

**Comment by camfindlay** [comment]
@SpiritLevel you'll want to touch base with @assertchris about that section of the contribution guide he has a bunch of work done and not yet in a pull request.

**Comment by camfindlay** [comment]
@SpiritLevel all rewrites returned a 200 response locally for the 50 urls except http://docs.dev/en/developer_guides/customising_the_admin_interface/reference/cms-architecture/

Work out how to correct that one and I think we are good.

**Comment by SpiritLevel** [comment]
OK. I will wait for the PR. How about I start on http://docs.silverstripe.org/en/3.1/ ? 

Cam, can you email me your test script. I have one using curl but I don't like how I test for 404.

OK. Will fix that last rewrite.

**Comment by SpiritLevel** [comment]
@camfindlay Which of the original 50 generated that one ? I have seen one with docs.dev before ?

**Comment by SpiritLevel** [comment]
I don't get the docs.dev on my machine ??? Is there a way to pin down the source url ?

**Comment by camfindlay** [comment]
Apologies, that is my local dev domain. mentally replace docs.dev with docs.silverstripe.org (though it's really the bit after that we're most interested in).

**Comment by SpiritLevel** [comment]
OK....:)

**Comment by camfindlay** [comment]
By  http://docs.silverstripe.org/en/3.1/ do you mean the intro page of docs? Sure, you can write and raise a PR. Given it's the "home" page of docs you might get a few comments as to the content I would imagine.

**Comment by camfindlay** [comment]
@SpiritLevel where did you get to with this one?

**Comment by SpiritLevel** [comment]
@camfindlay I fixed the last remaining one. How about run your test script to confirm and then merge!

**Comment by camfindlay** [comment]
Running now fyi I'm using this simple command with a txt file full of urls.

```
cat urls.txt | xargs -n 1 curl -0 -sL -w "%{http_code} %{url_effective}\\n" -o /dev/null
```

**Comment by SpiritLevel** [comment]
Thanks for that :)

**Comment by camfindlay** [comment]
Looks good

200 http://docs.dev/en/3.1/changelogs/
200 http://docs.dev/en/3.1/getting_started/composer/
200 http://addons.silverstripe.org/
200 http://docs.dev/en/3.1/developer_guides/security/authentication/
200 http://addons.silverstripe.org/add-ons/silverstripe/mssql
200 http://docs.dev/en/3.1/developer_guides/security/authentication/
200 http://docs.dev/en/3.1/developer_guides/templates/requirements/
200 http://docs.dev/en/3.1/developer_guides/forms/field_types/datefield/
200 http://docs.dev/en/3.1/developer_guides/security/member/
200 http://docs.dev/en/3.1/developer_guides/model/
200 http://docs.dev/en/3.1/developer_guides/forms/field_types/common_subclasses/
200 http://docs.dev/en/2.4/tutorials/building-a-basic-site
200 http://docs.dev/en/3.1/developer_guides/security/
200 http://docs.dev/en/3.1/getting_started/environment_management/
200 http://docs.dev/en/3.1/developer_guides/testing/
200 http://docs.dev/en/2.4/tutorials/extending-a-basic-site
200 http://docs.dev/en/3.1/developer_guides/configuration/
200 http://www.silverstripe.org/software/download
200 http://docs.dev/en/3.1/developer_guides/security/permissions/
200 http://docs.dev/en/3.1/developer_guides/controllers/
200 http://docs.dev/en/3.1/developer_guides/customising_the_admin_interface/typography/
200 http://docs.dev/en/3.1/developer_guides/
200 http://docs.dev/en/3.1/developer_guides/forms/field_types/htmleditorfield/
200 http://docs.dev/en/3.1/developer_guides/customising_the_admin_interface/modeladmin/
200 http://docs.dev/en/3.0/tutorials/dataobject-relationship-management
200 http://docs.dev/en/2.4/tutorials/dataobject-relationship-management
200 http://docs.dev/en/2.4/tutorials/forms
200 http://docs.dev/en/3.0/tutorials/extending-a-basic-site
200 http://docs.dev/en/2.4/reference/requirements
200 http://docs.dev/en/3.0/tutorials/building-a-basic-site
200 https://github.com/mattclegg/silverstripe-doc-restructuring/blob/master/output/modules/auth_ext_drivers.md
200 http://docs.dev/en/3.1/developer_guides/templates/syntax/
200 http://docs.dev/en/3.1/contributing/release_process/
200 http://docs.dev/en/3.1/developer_guides/model/
200 http://docs.dev/en/3.1/developer_guides/model/extending_dataobjects/
200 http://docs.dev/en/3.1/developer_guides/model/data_types_and_casting/
200 http://docs.dev/en/3.1/getting_started/composer/
200 http://docs.dev/en/3.1/upgrading/
200 http://docs.dev/en/3.0/tutorials/site-search
200 http://docs.dev/en/4.0/developer_guides/forms/field_types/gridfield
200 http://docs.dev/en/2.4/tutorials/site-search
200 http://docs.dev/en/3.1/developer_guides/customising_the_admin_interface/cms_architecture/
200 http://docs.dev/en/3.1/developer_guides/forms/field_types/common_subclasses/
200 http://docs.dev/en/3.1/developer_guides/forms/tabbed_forms/
200 http://docs.dev/en/3.1/developer_guides/extending/extensions/
200 http://docs.dev/en/3.1/developer_guides/templates/
200 http://docs.dev/en/3.1/developer_guides/customising_the_admin_interface/modeladmin/
200 http://docs.dev/en/3.1/developer_guides/model/sql_query/
200 http://docs.dev/en/3.1/upgrading/
200 http://docs.dev/en/3.1/developer_guides/model/data_model_and_orm/

**Comment by SpiritLevel** [comment]
Excellent. What's next ?

**Comment by camfindlay** [comment]
Deploy to the testing server, then to production after a few checks.

**Comment by SpiritLevel** [comment]
OK. I meant what is next on the priority list for docs.silverstripe.org that I can help with. I feel like getting stuff done and learning more.

**Comment by camfindlay** [comment]
Perhaps look at https://github.com/silverstripe/doc.silverstripe.org/issues or start taking via dev list to community for suggestions.

**Comment by SpiritLevel** [comment]
Which issue is most important to resolve ?

**Pull request merged**
