### PR TITLE
ENH Add Linkfield user docs

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/26

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Committed the change that will skip userguide in dev docs.

**Comment by GuySartorelli** [comment]
@sabina-talipova are you happy with the changes I made? If so, I will merge.

**Comment by sabina-talipova** [comment]
Yes, everything is perfect.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
