### PR TITLE
Issue 50 ( add rewrite rules for top 50 404 errors)

### PR DESCRIPTION
**Pull request by SpiritLevel**

### CODE REVIEW

**Comment by camfindlay** [comment]
Not too sure about commenting out all the past rewrites, many are there for a reason based on the urls of the old docs structure.

**Comment by SpiritLevel** [comment]
Understood :) But, can't we just merge these, re-run the top 50, confirm that I am getting the regexes correct for the docs.silverstripe.org server. Then, re-generate the top 50, and keep repeating this until all 404s are eliminated ? If you are worried about leaving too many 404s "live", I'll agree to attend to the list right away if you agree to keep merging and generating the new sets of top 50 ?

**Comment by camfindlay** [comment]
The top 50 are over and above the previous rewrites which we must continue to account for. So any pull request would have to:

1. Retain historic rewrites (otherwise if we remove these the net total of 404s will actually rise not fall).
2. Fix the listed top 50 in the #50 after which time we would close that issue and open a new one with a new set of rewrites to tackle.

If you want to re-structure how the historic rewrites are written for the sake of tidiness that is fine as long as they still do the same job.

Ends is what matter most, not means - in this case value to community is not getting 404s when they visit the docs site from old links.

**Comment by SpiritLevel** [comment]
OK. I'll put the historic rewrites back in; this will cost us in terms of many additional RewriteConds though :)

**Comment by camfindlay** [comment]
Can you give me an example?

**Comment by SpiritLevel** [comment]
Just doing them now. So far, the RewriteConds I already have are preventing loops! So, maybe no new ones are needed after all :)

**Comment by camfindlay** [comment]
I mean an example of a loop you are dealing with and your reasoning :)

**Comment by SpiritLevel** [comment]
All the loops are commented in the
      rules I added. Roughly 15 of them.
      
      On 14/07/15 11:28, Cam Findlay wrote:
    
    
      I mean an example of a loop you are dealing with and your
        reasoning :)
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by camfindlay** [comment]
Ok @SpiritLevel 

So with regards to this cond and rule as an example.

```
RewriteCond %{REQUEST_URI} !^(.*)/field_types/datefield
RewriteRule ^(.*)datefield/?$ /$1/en/developer_guides/forms/field_types/datefield [R=301,L]
```

The 404 we are fixing here is http://docsdomainhere/datefield only

So the rule will simply be:

```
RewriteRule ^datefield/?$ /en/developer_guides/forms/field_types/datefield [R=301,L]
```

It should only match http://docsdomainhere/datefield or http://docsdomainhere/datefield/
and the destination should not need to include the $1 since the incoming link is not providing us with any hint to a locale. In this case we default to our known /en/.

This means that (.*)/field_types/datefield won't match and cause a loop so no need for the extra RewriteCond.

You can test this over at http://htaccess.madewithlove.be/ :)

**Comment by SpiritLevel** [comment]
OK. Will check RewriteConds to see which can be eliminated :)

**Pull request closed without merging**
