### PR TITLE
NEW: Add canonical link for v3

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves https://github.com/silverstripe/doc.silverstripe.org/issues/221

### CODE REVIEW

**Comment by emteknetnz** [comment]
@unclecheese do we need to build a js dist file for this locally? or is this handle automatically post-merge?

**Comment by unclecheese** [comment]
No, Netlify builds it.

**Comment by emteknetnz** [comment]
OK code looks fine to me at a syntax level, I'm not too familiar at all with how this all works, though given it's a docs site and won't have adverse downstream change, it means merging this is kind of low risk - does it makes sense for me to now merge this and if something doesn't quite look right we'll fix with a 2nd PR?

**Comment by unclecheese** [comment]
Netlify puts all PRs on their own domain. I wonder if there's way for it to post those links here.

**Comment by unclecheese** [comment]
Yeah, check it out, @emteknetnz , there's a deploy link in the CI now.

Looks like it didn't generate it because it came from an "unknown" author.. This must be the first time I've done it from my unclecheese repo. :)

**Comment by emteknetnz** [comment]
I clicked on CI deploy link

When I go to `https://deploy-preview-227--ss-docs.netlify.app/`
Then I am redirected to `https://deploy-preview-227--ss-docs.netlify.app/en/4/`

Sweet 👍

**Pull request merged**
