### PR TITLE
New version of docs into production master branch

### PR DESCRIPTION
**Pull request by camfindlay**
@wilr anything else we need to add here before we make this the master branch? I have tagged the current master with a 0.1, given this is a major overhaul I'd say we tag this update as 1.0.0

### CODE REVIEW

**Comment by camfindlay** [comment]
looks like I'll need to rebase and resolve conflicts on this PR first.

**Comment by camfindlay** [comment]
@wilr ok rebased this project branch - are you happy for this to be merged and a 1.0.0 release of the docs project tagged? I've deployed this to beta server and seems to be running well.

**Comment by wilr** [comment]
Ok 1.0.0 with old doc.silverstripe.org tagged and 2.0.0 tagged for this new version.

**Comment by camfindlay** [comment]
want me to do the tagging @wilr ?

**Comment by camfindlay** [comment]
scratch that, I see you've sorted it.

**Pull request merged**
