### PR TITLE
Cosmetics (see #80)

### PR DESCRIPTION
**Pull request by SpiritLevel**

### CODE REVIEW

**Comment by camfindlay** [comment]
thanks @SpiritLevel will look at these in upcoming hackday. FYI, we have a public hack coming up you might want to attend, check the Wellington meetup group.

**Comment by camfindlay** [comment]
Can you give me a quick screenshot as to what this looks like locally?

**Comment by SpiritLevel** [comment]
screenshot from 2015-10-22 09 47 53

Font size is a bit big though.

**Comment by camfindlay** [comment]
Perhaps the version label should be more subtle? Also how does this look on mobile?
We had the versions lining up with the side nav

**Comment by SpiritLevel** [comment]
Hi Cam....just looking at docs.silverstripe.org on mobile now and there is no side nav...also, the top menu and version numbers are microscopic in portrait! Very hard to read. Landscape is tolerable. Same with items under "SilverStripe Concepts" and "Contributing to SilverStripe". The archive dropdown at  top and buttons at the bottom are microscopic too. If you want docs.silverstripe.org to have a responsive design then it appears a bit of layout work is needed!

**Comment by SpiritLevel** [comment]
And, it would be nice to get https://github.com/silverstripe/silverstripe-docsviewer/pull/74 in :)

**Comment by camfindlay** [comment]
Yep the top nav needs responsive work across all the docs related sites (it's pulled in from a statically generated copy from the main silverstripe.org website.

Can look to add these labels if you think it makes it clearer the numbers are version numbers (I excluded adding a "Versions" as I though it was a bit cleaner.

**Comment by SpiritLevel** [comment]
Personally, I like trivial things to be crystal clear so that I don't have to spend any time at all thinking about what they mean ;) So I'd put in a heading like "Versions" or "Version" or "Documentation Versions" or something in the title "SilverStripe Developer Documentation Version 3.2"...anything to make it clear that one can select which version of the docs to read.. Also, once a version is selected, one should be able to see the selected version from wherever they are in the docs and the HOME button should keep one within that version choice, which is the reason for https://github.com/silverstripe/silverstripe-docsviewer/pull/74. 

@camfindlay What is happening with docsviewer anyway ? There are few old PRs and lots of red X's :(

**Comment by camfindlay** [comment]
Docviewer unit tests are tracking against the 3 branch of core (future 3.3) hence the red Xs. We need to perhaps update the travis CI config.

**Comment by SpiritLevel** [comment]
Would the config file be .travis.yml ? And are the updates needed those given in 
https://github.com/silverstripe-labs/silverstripe-travis-support#travis-setup ?

**Pull request merged**
